# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bumptag < Formula
  desc "bumptag is a tool to increment a version and to create a git tag with an annotation"
  homepage "https://github.com/sv-tools/grade"
  version "1.8.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/sv-tools/bumptag/releases/download/v1.8.0/bumptag-v1.8.0-darwin-amd64.tar.gz"
    sha256 "28def98451820726e6369d72d108fa7998b084b30c86f2c75907fdbdd7dbb8a0"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/sv-tools/bumptag/releases/download/v1.8.0/bumptag-v1.8.0-darwin-arm64.tar.gz"
    sha256 "e434509ae45a0baca6af7819f5db19bad0cb7d194485c84fc99421b4f7ada9fa"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/sv-tools/bumptag/releases/download/v1.8.0/bumptag-v1.8.0-linux-amd64.tar.gz"
    sha256 "04280aab8afdb9b90779b679ca6988644ebf046db2ce217e0e9a4f01bd0e7977"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/sv-tools/bumptag/releases/download/v1.8.0/bumptag-v1.8.0-linux-arm64.tar.gz"
    sha256 "b8b07946934085284814218fb9852879173ad194f0ead7027ab9b14cdbb5b4f5"
  end

  def install
    bin.install "bumptag"
  end

  test do
    assert_equal `#{bin}/bumptag --version`, "bumptag version v#{version}"
  end
end
