# This file was generated by GoReleaser. DO NOT EDIT.
class Grade < Formula
  desc "grade transforms Go benchmark data into various format so that you can uploads the data to a database and track the performance over time."
  homepage "https://github.com/sv-go-tools/grade"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sv-go-tools/grade/releases/download/v0.1.0/grade-v0.1.0-darwin-amd64.tar.gz"
    sha256 "087e20e304dbfb16e202a45cd19f77fd270689ef13cf1c3bb42adbd67a4913a2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sv-go-tools/grade/releases/download/v0.1.0/grade-v0.1.0-linux-amd64.tar.gz"
      sha256 "5c46a1bb35943ca4666539ae55c7057a8a5630fa3ee7852a8dbc21108118dabc"
    end
  end

  def install
    bin.install "grade"
  end

  test do
    assert_equal `#{bin}/grade --version`, "grade version v#{version}"
  end
end
